var ss = require('./index.js');

var pages = [
    'http://www.lmo.com/',
    'http://www.lmo.com/about',
    'http://www.lmo.com/about/culture',
    'http://www.lmo.com/about/leadership',
    'http://www.lmo.com/about/leadership/chris-laughlin',
    'http://www.lmo.com/about/leadership/mike-kapetanovic',
    'http://www.lmo.com/admen',
    'http://www.lmo.com/admen/about-dave',
    'http://www.lmo.com/admen/freechapter',
    'http://www.lmo.com/admen/read-the-reviews',
    'http://www.lmo.com/bigdiagnostics',
    'http://www.lmo.com/blog',
    'http://www.lmo.com/blog/category/associations',
    'http://www.lmo.com/blog/category/financial-services',
    'http://www.lmo.com/blog/category/government',
    'http://www.lmo.com/blog/category/insights',
    'http://www.lmo.com/blog/category/news',
    'http://www.lmo.com/blog/category/non-profit',
    'http://www.lmo.com/blog/category/past',
    'http://www.lmo.com/blog/category/tourism',
    'http://www.lmo.com/blog/google-analytics-certification',
    'http://www.lmo.com/blog/is-programmatic-tv-the-future-of-tv-media-buying',
    'http://www.lmo.com/careers',
    'http://www.lmo.com/careers/assistant-advertising-operations-ad-ops-specialist',
    'http://www.lmo.com/careers/business-intelligence-developer-2',
    'http://www.lmo.com/careers/junior-content-marketing-manager',
    'http://www.lmo.com/careers/media-planner-buyer-2',
    'http://www.lmo.com/contact',
    'http://www.lmo.com/privacy-policy',
    'http://www.lmo.com/services',
    'http://www.lmo.com/services/federal',
    'http://www.lmo.com/work',
    'http://www.lmo.com/work/apa-style-central-responsive-landing-page',
    'http://www.lmo.com/work/category/associations',
    'http://www.lmo.com/work/category/financial',
    'http://www.lmo.com/work/category/government',
    'http://www.lmo.com/work/category/medical',
    'http://www.lmo.com/work/category/non-profit',
    'http://www.lmo.com/work/category/other',
    'http://www.lmo.com/work/category/travel',
    'http://www.lmo.com/work/evermay-responsive-website-redesign',
]

go();
